--- name:default
# Time in s between depth_map readings
depth_map_period: 0.1
# the global name that should be used for the internal laser frame
laser_frame: laser
# Selects the type of odometry based motion compensation
motion_compensation: :Horizontal #:HorizontalInterpolation #:NoCompensation #:Horizontal
# the global name that should be used for the internal odometry frame
odometry_frame: odometry
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 1.0
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
